### PR TITLE
Add missing static 404 image

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add missing SVG static image following https://github.com/PrestaShop/ps-docs-theme/pull/2
| Type?             | bugfix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/docs/issues/870
| How to test?      | Builds the site, then visit a 404 page.
| Possible impacts? |

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Comment by matks** [comment]
This time I hope it's going to work 😄 locally I had to do some tricks to get it working so it's hard to make sure it's going to be OK for production.

**Comment by matks** [comment]
Aaaaaah I get it 😄 I thought "static" was a folder automatically generated.

But no.

The `images/` folder is for images used in the README, the `static/images/` folder is for images used in the theme.

**Comment by matks** [comment]
Thank you

**Comment by matks** [comment]
Fixed https://devdocs.prestashop.com/ajdh

**Pull request merged**
